version: 2.1
jobs:
  build-back:
    docker:
      - image: circleci/node:16 # node버전
    working_directory: ~/cicd_circle-argo/back
    steps:
      - checkout
      - restore_cache
          keys:
            - dep-bundle-{{ checksum "package.json"}}
      - run: 
          name: install
          command: yarn install
      - save_cache
          paths:
            - node_modules
          keys:
            - dep-bundle-{{ checksum "package.json"}}
      - run:
          name: build
          command: yarn build
workflows:
  back-CI:
    jobs:
      - build-back
